name: golangci-lint
on:
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # can setup
      - name: Enable universe repository and Install libgit2-1.7
        run: |
          sudo add-apt-repository ppa:savoury1/build-tools -y
          sudo apt-get update
          sudo apt-get install libgit2-1.7 libgit2-dev -y
          libgit2_version=$(dpkg-query -W -f='${Version}' libgit2-1.7)
          echo "libgit2-1.7 version: $libgit2_version"

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: run
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: true
          args: --timeout 10m
